name: restaurant_app
description: Demo flutter project


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  bloc: ^7.2.1
  flutter_bloc: ^7.3.0
  geolocator: 7.6.2
  map: ^1.0.0
  latlng: ^0.1.0
  cached_network_image: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true


